# Generated by Django 5.2.7 on 2025-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_cyti_user_city_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличные"), ("transfer", "перевод")],
                max_length=50,
                verbose_name="Метод платежа",
            ),
        ),
    ]
