# Generated by Django 5.2.7 on 2025-11-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_lesson_url"),
        ("users", "0005_paymcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymcourse",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
