# Generated by Django 5.2.7 on 2025-10-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson",
            new_name="course",
        ),
    ]
