# Generated by Django 5.2.7 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Загрузите ссылку",
                null=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
