# Generated by Django 5.2.8 on 2025-11-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_lesson_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Время последнего обновления"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Загрузите видео",
                null=True,
                upload_to="materials/media",
            ),
        ),
    ]
